### ISSUE TITLE
middle-click on command in list does not work as expected

### ISSUE THREAD

**Issue by badboy** [aaronblohowiak/evalsha#1]
By default middle-clicking a link opens the href in a new tab. This does not work in the [commands list](http://evalsha.com/commands) as it uses `onclick="window.location.href=..."`

There are different solutions:
1. Use a proper a-tag surrounding the name (and the sha). Middle-click works by default
2. Use unobtrusive javascript to bind an event handler to each `<tr>` checking for event.which to do the right thing on middle-click

The easiest version would be 1., but you lose the abilty to click the whole line.
Any thoughts on this?

**Comment by aaronblohowiak** [comment]
Your working code will trump my opinion. Note that I don't have nor want any heavy js frameworks (redis is fast so evalsha.com should be fast) so the a-tag approach is probably best.
