### ISSUE TITLE
Spamming

### ISSUE THREAD

**Issue by mountain** [aaronblohowiak/evalsha#3]
Right now the site are suffering with spamming!

**Comment by aaronblohowiak** [comment]
I would like to keep the barrier to contributing very low if possible, so I don't want to make it hard for people to contribute -- not sure what the best way a) prevent spam and b) make it painless to contribute is.  I have thought about using Github for auth.. what do you think?

**Comment by dgershman** [comment]
how about a captcha?

**Comment by frankamp** [comment]
a captcha where the user must evaluate code! because machines are terrible at... oh. nevermind.

**Comment by aaronblohowiak** [comment]
LOL.  I tried recaptcha 0.3.4, but it is tightly bound to Rails.  Would
accept a pull request !
- Aaron

**Comment by mikemccabe** [comment]
perhaps you could require that submitted code be syntax-error-free Lua?

**Comment by aaronblohowiak** [comment]
Excellent suggestion! What lua syntax checker would you recommend?

**Comment by plambert** [comment]
Would https://code.google.com/p/lua-checker/ meet your needs?

**Comment by kmatt** [comment]
Can the code be EVALed in a Redis instance as a check?

**Comment by jimktrains** [comment]
What about something like AskiMet?

There is also https://github.com/achiu/rack-recaptcha that plugs into Rack and not rails.

**Comment by jimktrains** [comment]
Also, perhaps tossing out any script that has HTML in it?

**Comment by aaronblohowiak** [comment]
Pull requests gladly accepted :D

**Comment by aaronblohowiak** [comment]
There is already a bit of rejection code -- i think rejecting html stuff is
the easiest way to go

**Comment by aaronblohowiak** [comment]
Thanks for the offers. It should be fine now. Please email me aaron.blohowiak@gmail.com if you notice any more spam. I've merged an PR that blocks '<a', '<p' and 'http:'. If you want to make it so github-authorized contributors are free from these checks, I will gladly merge the pull request.
