### ISSUE TITLE
Help moderating available

### ISSUE THREAD

**Issue by jimktrains** [aaronblohowiak/evalsha#6]
I love the idea of the site, but the spam will kill any chance it has.  I can help moderate, if that's a possibility.  I can go through daily, at least, and clean out spam.

**Comment by josegonzalez** [comment]
+1 I can help moderate it. We can at the very least disallow anything that has a url in it.

**Comment by aaronblohowiak** [comment]
Thanks for the offers.  It should be fine now.  Please email me aaron.blohowiak@gmail.com if you notice any more spam.  I've merged an PR that blocks '<a', '<p' and 'http:'.  If you want to make it so github-authorized contributors are free from these checks, I will gladly merge the pull request.
